name: build atm docker image

on:
  workflow_dispatch:
    inputs:
      docker_image_version:
        type: string
        description: docker image's version
        required: true
jobs:
  login_and_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # i don't know what it is but it needs it
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_DOCKER_REGISTRY_KEY }}
      # https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            latest
            ${{ github.event.inputs.docker_image_version }}
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}